In [1]:
import pandas as pd

In [2]:
print("hello world")

hello world

In [3]:
print(' hellow world is \n how \n are you')

 hellow world is
 how
 are you

In [4]:
import pandas as pd

url = "https://bollymoviereviewz.com/2013/04/bollywood-box-office-collection-2013.html"

tables = pd.read_html(url)

print(len(tables))

2

In [5]:
for i, table in enumerate(tables):
    print("TABLE:", i)
    print(table.head())

TABLE: 0
               Movie Name Box Office Collection Budget (Cost+ P&A)  \
0          Toxic ( Hindi)          133.75 Crore          500 Crore
1            Hanuman Ansh        68 to 69 Crore           10 Crore
2          Mirzapur Movie          Good Advance                  —
3  Toxic ( All Languages)             231 Crore          500 Crore
4              Awarapan 2          144.15 Crore           45 Crore

  Verdict (Hit Ya Flop)
0                     —
1                     —
2                     —
3                     —
4             Super Hit
TABLE: 1
              Movie Name Box Office Collection Budget (Cost+ P&A)  \
0           Batwara 1947           34.66 Crore          120 Crore
1            Insidious 6            12.8 Crore          172 Crore
2            The Odyssey          179.58 Crore         2406 Crore
3  The End of Oak Street            5.25 Crore          811 Crore
4              Dhamaal 4          161.15 Crore          150 Crore

  Verdict (Hit Ya Flop)
0              Disaster
1                     —
2             Super Hit
3                  Flop
4                   Hit

In [6]:
df = tables[1]

In [7]:
df

,Movie Name,Box Office Collection,Budget (Cost+ P&A),Verdict (Hit Ya Flop)
0,Batwara 1947,34.66 Crore,120 Crore,Disaster
1,Insidious 6,12.8 Crore,172 Crore,—
2,The Odyssey,179.58 Crore,2406 Crore,Super Hit
3,The End of Oak Street,5.25 Crore,811 Crore,Flop
4,Dhamaal 4,161.15 Crore,150 Crore,Hit
...,...,...,...,...
265,Hanu Man (Hindi),50.76 Crore,50 Crore,Super Hit
266,Dunki,212.8 Crore,200 Crore,Hit
267,Main Atal Hoon,6.4 Crore,25 Crore,Flop
268,Merry Christmas,16 Crore,60 Crore,Disaster
269,Salaar (Hindi),148.49 Crore,80 Crore,Hit

In [8]:
df.head()

,Movie Name,Box Office Collection,Budget (Cost+ P&A),Verdict (Hit Ya Flop)
0,Batwara 1947,34.66 Crore,120 Crore,Disaster
1,Insidious 6,12.8 Crore,172 Crore,—
2,The Odyssey,179.58 Crore,2406 Crore,Super Hit
3,The End of Oak Street,5.25 Crore,811 Crore,Flop
4,Dhamaal 4,161.15 Crore,150 Crore,Hit

In [9]:
df.shape

(270, 4)

In [10]:
import pandas as pd

url = "https://bollymoviereviewz.com/2013/04/bollywood-box-office-collection-2013.html"

tables = pd.read_html(url)

print("Number of tables:", len(tables))

for i, table in enumerate(tables):
    print("\nTable:", i)
    print("Rows:", len(table))
    print("Columns:", table.columns.tolist())
    print(table.head(3))

Number of tables: 2

Table: 0
Rows: 6
Columns: ['Movie Name', 'Box Office Collection', 'Budget (Cost+ P&A)', 'Verdict (Hit Ya Flop)']
       Movie Name Box Office Collection Budget (Cost+ P&A)  \
0  Toxic ( Hindi)          133.75 Crore          500 Crore
1    Hanuman Ansh        68 to 69 Crore           10 Crore
2  Mirzapur Movie          Good Advance                  —

  Verdict (Hit Ya Flop)
0                     —
1                     —
2                     —

Table: 1
Rows: 270
Columns: ['Movie Name', 'Box Office Collection', 'Budget (Cost+ P&A)', 'Verdict (Hit Ya Flop)']
     Movie Name Box Office Collection Budget (Cost+ P&A) Verdict (Hit Ya Flop)
0  Batwara 1947           34.66 Crore          120 Crore              Disaster
1   Insidious 6            12.8 Crore          172 Crore                     —
2   The Odyssey          179.58 Crore         2406 Crore             Super Hit

In [11]:
import pandas as pd

url = "https://bollymoviereviewz.com/2013/04/bollywood-box-office-collection-2013.html"

tables = pd.read_html(url)

print("Number of tables:", len(tables))

for i, table in enumerate(tables):
    print("\n----------------")
    print("TABLE:", i)
    print("Rows:", table.shape[0])
    print("Columns:", table.shape[1])
    print(table.head(3))

Number of tables: 2

----------------
TABLE: 0
Rows: 6
Columns: 4
       Movie Name Box Office Collection Budget (Cost+ P&A)  \
0  Toxic ( Hindi)          133.75 Crore          500 Crore
1    Hanuman Ansh        68 to 69 Crore           10 Crore
2  Mirzapur Movie          Good Advance                  —

  Verdict (Hit Ya Flop)
0                     —
1                     —
2                     —

----------------
TABLE: 1
Rows: 270
Columns: 4
     Movie Name Box Office Collection Budget (Cost+ P&A) Verdict (Hit Ya Flop)
0  Batwara 1947           34.66 Crore          120 Crore              Disaster
1   Insidious 6            12.8 Crore          172 Crore                     —
2   The Odyssey          179.58 Crore         2406 Crore             Super Hit

In [12]:
print(tables[1].tail(10))

                           Movie Name Box Office Collection  \
260  Teri Baaton Mein Aisa Uljha Jiya              78 Crore
261                    Laapata Ladies           15.94 Crore
262                            Dune 2           14.44 Crore
263                             Crakk            12.6 Crore
264                           Fighter           200.1 Crore
265                  Hanu Man (Hindi)           50.76 Crore
266                             Dunki           212.8 Crore
267                    Main Atal Hoon             6.4 Crore
268                   Merry Christmas              16 Crore
269                    Salaar (Hindi)          148.49 Crore

    Budget (Cost+ P&A) Verdict (Hit Ya Flop)
260           85 Crore               Average
261           40 Crore                  Flop
262         1580 Crore               Average
263           80 Crore                  Flop
264          200 Crore                   Hit
265           50 Crore             Super Hit
266          200 Crore                   Hit
267           25 Crore                  Flop
268           60 Crore              Disaster
269           80 Crore                   Hit

In [13]:
df = pd.concat(tables, ignore_index=True)

In [14]:
df

,Movie Name,Box Office Collection,Budget (Cost+ P&A),Verdict (Hit Ya Flop)
0,Toxic ( Hindi),133.75 Crore,500 Crore,—
1,Hanuman Ansh,68 to 69 Crore,10 Crore,—
2,Mirzapur Movie,Good Advance,—,—
3,Toxic ( All Languages),231 Crore,500 Crore,—
4,Awarapan 2,144.15 Crore,45 Crore,Super Hit
...,...,...,...,...
271,Hanu Man (Hindi),50.76 Crore,50 Crore,Super Hit
272,Dunki,212.8 Crore,200 Crore,Hit
273,Main Atal Hoon,6.4 Crore,25 Crore,Flop
274,Merry Christmas,16 Crore,60 Crore,Disaster
275,Salaar (Hindi),148.49 Crore,80 Crore,Hit

In [13]:
df.shape

(269, 4)

In [15]:
df.head(20)

,Movie Name,Box Office Collection,Budget (Cost+ P&A),Verdict (Hit Ya Flop)
0,Toxic ( Hindi),133.75 Crore,500 Crore,—
1,Hanuman Ansh,68 to 69 Crore,10 Crore,—
2,Mirzapur Movie,Good Advance,—,—
3,Toxic ( All Languages),231 Crore,500 Crore,—
4,Awarapan 2,144.15 Crore,45 Crore,Super Hit
5,Spiderman Brand New Day,471.7 Crore,2151 Crore,All Time Blockbuster
6,Batwara 1947,34.66 Crore,120 Crore,Disaster
7,Insidious 6,12.8 Crore,172 Crore,—
8,The Odyssey,179.58 Crore,2406 Crore,Super Hit
9,The End of Oak Street,5.25 Crore,811 Crore,Flop
10,Dhamaal 4,161.15 Crore,150 Crore,Hit
11,Jana Neta ( Hindi),17.1 Crore,400 Crore,Flop
12,Jana Nayagan ( All Languages),198 Crore,400 Crore,Average
13,Welcome to The Jungle,129.5 Crore,125 Crore,Hit
14,Alpha,56.7 Crore,150 Crore,Flop
15,Cocktail 2,88.2 Crore,150 Crore,Flop
16,Ohh My Dog,4.5 Crore,25 Crore,Flop
17,Aryabhatt Ka Zero,0.62 Crore,25 Crore,Flop
18,Main Vaapas Aaunga,58.55 Crore,70 Crore,Average
19,Bhai Tera Star Hai,1.15 Crore,25 Crore,Flop

In [16]:
df.dtypes

Movie Name               str
Box Office Collection    str
Budget (Cost+ P&A)       str
Verdict (Hit Ya Flop)    str
dtype: object

In [17]:
url= 'https://books.toscrape.com/catalogue/category/books/religion_12/index.html'

In [18]:
tables= pd.read_html(url)

ValueError: No tables found

In [19]:
print(len(table))

270

In [20]:
tables

[                Movie Name Box Office Collection Budget (Cost+ P&A)  \
 0           Toxic ( Hindi)          133.75 Crore          500 Crore
 1             Hanuman Ansh        68 to 69 Crore           10 Crore
 2           Mirzapur Movie          Good Advance                  —
 3   Toxic ( All Languages)             231 Crore          500 Crore
 4               Awarapan 2          144.15 Crore           45 Crore
 5  Spiderman Brand New Day           471.7 Crore         2151 Crore

   Verdict (Hit Ya Flop)
 0                     —
 1                     —
 2                     —
 3                     —
 4             Super Hit
 5  All Time Blockbuster  ,
                 Movie Name Box Office Collection Budget (Cost+ P&A)  \
 0             Batwara 1947           34.66 Crore          120 Crore
 1              Insidious 6            12.8 Crore          172 Crore
 2              The Odyssey          179.58 Crore         2406 Crore
 3    The End of Oak Street            5.25 Crore          811 Crore
 4                Dhamaal 4          161.15 Crore          150 Crore
 ..                     ...                   ...                ...
 265       Hanu Man (Hindi)           50.76 Crore           50 Crore
 266                  Dunki           212.8 Crore          200 Crore
 267         Main Atal Hoon             6.4 Crore           25 Crore
 268        Merry Christmas              16 Crore           60 Crore
 269         Salaar (Hindi)          148.49 Crore           80 Crore

     Verdict (Hit Ya Flop)
 0                Disaster
 1                       —
 2               Super Hit
 3                    Flop
 4                     Hit
 ..                    ...
 265             Super Hit
 266                   Hit
 267                  Flop
 268              Disaster
 269                   Hit

 [270 rows x 4 columns]]

In [21]:
import  html5lib

In [22]:
import requests
from bs4 import BeautifulSoup

In [23]:
url= "https://books.toscrape.com/catalogue/category/books/religion_12/index.html"

In [24]:

tables = pd.read_html(url)
url= "https://books.toscrape.com/catalogue/category/books/religion_12/index.html"
print(type(tables))
print(type(tables[0]))

ValueError: No tables found

In [52]:
print(len(tables))

74

In [53]:
for i, table in enumerate(tables):
        print("\n----------------")
        print("TABLE:", i)

----------------
TABLE: 0

----------------
TABLE: 1

----------------
TABLE: 2

----------------
TABLE: 3

----------------
TABLE: 4

----------------
TABLE: 5

----------------
TABLE: 6

----------------
TABLE: 7

----------------
TABLE: 8

----------------
TABLE: 9

----------------
TABLE: 10

----------------
TABLE: 11

----------------
TABLE: 12

----------------
TABLE: 13

----------------
TABLE: 14

----------------
TABLE: 15

----------------
TABLE: 16

----------------
TABLE: 17

----------------
TABLE: 18

----------------
TABLE: 19

----------------
TABLE: 20

----------------
TABLE: 21

----------------
TABLE: 22

----------------
TABLE: 23

----------------
TABLE: 24

----------------
TABLE: 25

----------------
TABLE: 26

----------------
TABLE: 27

----------------
TABLE: 28

----------------
TABLE: 29

----------------
TABLE: 30

----------------
TABLE: 31

----------------
TABLE: 32

----------------
TABLE: 33

----------------
TABLE: 34

----------------
TABLE: 35

----------------
TABLE: 36

----------------
TABLE: 37

----------------
TABLE: 38

----------------
TABLE: 39

----------------
TABLE: 40

----------------
TABLE: 41

----------------
TABLE: 42

----------------
TABLE: 43

----------------
TABLE: 44

----------------
TABLE: 45

----------------
TABLE: 46

----------------
TABLE: 47

----------------
TABLE: 48

----------------
TABLE: 49

----------------
TABLE: 50

----------------
TABLE: 51

----------------
TABLE: 52

----------------
TABLE: 53

----------------
TABLE: 54

----------------
TABLE: 55

----------------
TABLE: 56

----------------
TABLE: 57

----------------
TABLE: 58

----------------
TABLE: 59

----------------
TABLE: 60

----------------
TABLE: 61

----------------
TABLE: 62

----------------
TABLE: 63

----------------
TABLE: 64

----------------
TABLE: 65

----------------
TABLE: 66

----------------
TABLE: 67

----------------
TABLE: 68

----------------
TABLE: 69

----------------
TABLE: 70

----------------
TABLE: 71

----------------
TABLE: 72

----------------
TABLE: 73

In [54]:
print(table.head())

AttributeError: 'str' object has no attribute 'head'

In [38]:
print("TABLE:", i)

TABLE: 73

In [55]:
import pandas as pd

url = "https://books.toscrape.com/catalogue/category/books/religion_12/index.html"

tables = pd.read_html(url)

print(type(tables))
print(type(tables[0]))

ValueError: No tables found

In [40]:
for i, table in enumerate(tables):
        print("\n----------------")
        print("TABLE:", i)
        print("Rows:", table.shape[0])
        print("Columns:", table.shape[1])
        print(table.head(3))

----------------
TABLE: 0

AttributeError: 'str' object has no attribute 'shape'

In [ ]:
import pandas as pd

url = "YOUR_URL"

tables = pd.read_html(url)

print(type(tables))
print(type(tables[0]))

In [56]:
import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/catalogue/category/books/religion_12/index.html"

response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

200

In [57]:
books = soup.select("article.product_pod")

print(len(books))

7

In [58]:
book = books[0]

name = book.select_one("h3 a")["title"]
price = book.select_one(".price_color").get_text(strip=True)
rating = book.select_one("p.star-rating")["class"]

print(name)
print(price)
print(rating)

Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master
Â£37.97
['star-rating', 'Two']

In [59]:
data = []

for book in books:

    name = book.select_one("h3 a")["title"]

    price = book.select_one(".price_color").get_text(strip=True)

    rating = book.select_one("p.star-rating")["class"][-1]

    data.append({
        "book_name": name,
        "price": price,
        "rating": rating
    })

In [60]:
df = pd.DataFrame(data)

print(df)

                                           book_name    price rating
0  Don't Be a Jerk: And Other Practical Advice fr...  Â£37.97    Two
1  You Are What You Love: The Spiritual Power of ...  Â£21.87   Four
2  God: The Most Unpleasant Character in All Fiction  Â£30.03   Five
3                                 The Book of Mormon  Â£24.57  Three
4  A History of God: The 4,000-Year Quest of Juda...  Â£27.62    One
5                                  The Bhagavad Gita  Â£57.49  Three
6  Choosing Our Religion: The Spiritual Lives of ...  Â£28.42   Four

In [61]:
df

                                           book_name    price rating
0  Don't Be a Jerk: And Other Practical Advice fr...  Â£37.97    Two
1  You Are What You Love: The Spiritual Power of ...  Â£21.87   Four
2  God: The Most Unpleasant Character in All Fiction  Â£30.03   Five
3                                 The Book of Mormon  Â£24.57  Three
4  A History of God: The 4,000-Year Quest of Juda...  Â£27.62    One
5                                  The Bhagavad Gita  Â£57.49  Three
6  Choosing Our Religion: The Spiritual Lives of ...  Â£28.42   Four

In [62]:
url = "https://books.toscrape.com/catalogue/page-1.html"

In [63]:
response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

books = soup.select("article.product_pod")

print(len(books))

20

In [64]:
for page in range(1, 51):

    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    # request page
    # extract books
    # append to data

In [65]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/catalogue/page-1.html"

response = requests.get(url)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

books = soup.select("article.product_pod")

print("Books found:", len(books))

Books found: 20

In [66]:
data = []

for book in books:

    name = book.select_one("h3 a")["title"]

    price = book.select_one(".price_color").get_text(strip=True)

    rating = book.select_one("p.star-rating")["class"][-1]

    availability = book.select_one(".availability").get_text(" ", strip=True)

    url = book.select_one("h3 a")["href"]

    data.append({
        "book_name": name,
        "price": price,
        "rating": rating,
        "availability": availability,
        "url": url
    })

df = pd.DataFrame(data)

print(df.head())

                               book_name    price rating availability  \
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

                                                 url
0               a-light-in-the-attic_1000/index.html
1                  tipping-the-velvet_999/index.html
2                          soumission_998/index.html
3                       sharp-objects_997/index.html
4  sapiens-a-brief-history-of-humankind_996/index...

In [67]:
for page in range(1, 51):

    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    print(url)

https://books.toscrape.com/catalogue/page-1.html
https://books.toscrape.com/catalogue/page-2.html
https://books.toscrape.com/catalogue/page-3.html
https://books.toscrape.com/catalogue/page-4.html
https://books.toscrape.com/catalogue/page-5.html
https://books.toscrape.com/catalogue/page-6.html
https://books.toscrape.com/catalogue/page-7.html
https://books.toscrape.com/catalogue/page-8.html
https://books.toscrape.com/catalogue/page-9.html
https://books.toscrape.com/catalogue/page-10.html
https://books.toscrape.com/catalogue/page-11.html
https://books.toscrape.com/catalogue/page-12.html
https://books.toscrape.com/catalogue/page-13.html
https://books.toscrape.com/catalogue/page-14.html
https://books.toscrape.com/catalogue/page-15.html
https://books.toscrape.com/catalogue/page-16.html
https://books.toscrape.com/catalogue/page-17.html
https://books.toscrape.com/catalogue/page-18.html
https://books.toscrape.com/catalogue/page-19.html
https://books.toscrape.com/catalogue/page-20.html
https://books.toscrape.com/catalogue/page-21.html
https://books.toscrape.com/catalogue/page-22.html
https://books.toscrape.com/catalogue/page-23.html
https://books.toscrape.com/catalogue/page-24.html
https://books.toscrape.com/catalogue/page-25.html
https://books.toscrape.com/catalogue/page-26.html
https://books.toscrape.com/catalogue/page-27.html
https://books.toscrape.com/catalogue/page-28.html
https://books.toscrape.com/catalogue/page-29.html
https://books.toscrape.com/catalogue/page-30.html
https://books.toscrape.com/catalogue/page-31.html
https://books.toscrape.com/catalogue/page-32.html
https://books.toscrape.com/catalogue/page-33.html
https://books.toscrape.com/catalogue/page-34.html
https://books.toscrape.com/catalogue/page-35.html
https://books.toscrape.com/catalogue/page-36.html
https://books.toscrape.com/catalogue/page-37.html
https://books.toscrape.com/catalogue/page-38.html
https://books.toscrape.com/catalogue/page-39.html
https://books.toscrape.com/catalogue/page-40.html
https://books.toscrape.com/catalogue/page-41.html
https://books.toscrape.com/catalogue/page-42.html
https://books.toscrape.com/catalogue/page-43.html
https://books.toscrape.com/catalogue/page-44.html
https://books.toscrape.com/catalogue/page-45.html
https://books.toscrape.com/catalogue/page-46.html
https://books.toscrape.com/catalogue/page-47.html
https://books.toscrape.com/catalogue/page-48.html
https://books.toscrape.com/catalogue/page-49.html
https://books.toscrape.com/catalogue/page-50.html

In [68]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data = []

for page in range(1, 51):

    url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.select("article.product_pod")

    print(f"Page {page}: {len(books)} books")

    for book in books:

        name = book.select_one("h3 a")["title"]

        price = book.select_one(".price_color").get_text(strip=True)

        rating = book.select_one("p.star-rating")["class"][-1]

        availability = book.select_one(
            ".availability"
        ).get_text(" ", strip=True)

        product_url = book.select_one("h3 a")["href"]

        data.append({
            "book_name": name,
            "price": price,
            "rating": rating,
            "availability": availability,
            "url": product_url
        })

df = pd.DataFrame(data)

print("\nTotal books:", len(df))

Page 1: 20 books
Page 2: 20 books
Page 3: 20 books
Page 4: 20 books
Page 5: 20 books
Page 6: 20 books
Page 7: 20 books
Page 8: 20 books
Page 9: 20 books
Page 10: 20 books
Page 11: 20 books
Page 12: 20 books
Page 13: 20 books
Page 14: 20 books
Page 15: 20 books
Page 16: 20 books
Page 17: 20 books
Page 18: 20 books
Page 19: 20 books
Page 20: 20 books
Page 21: 20 books
Page 22: 20 books
Page 23: 20 books
Page 24: 20 books
Page 25: 20 books
Page 26: 20 books
Page 27: 20 books
Page 28: 20 books
Page 29: 20 books
Page 30: 20 books
Page 31: 20 books
Page 32: 20 books
Page 33: 20 books
Page 34: 20 books
Page 35: 20 books
Page 36: 20 books
Page 37: 20 books
Page 38: 20 books
Page 39: 20 books
Page 40: 20 books
Page 41: 20 books
Page 42: 20 books
Page 43: 20 books
Page 44: 20 books
Page 45: 20 books
Page 46: 20 books
Page 47: 20 books
Page 48: 20 books
Page 49: 20 books
Page 50: 20 books

Total books: 1000

In [69]:
df.head()

,book_name,price,rating,availability,url
0,A Light in the Attic,Â£51.77,Three,In stock,a-light-in-the-attic_1000/index.html
1,Tipping the Velvet,Â£53.74,One,In stock,tipping-the-velvet_999/index.html
2,Soumission,Â£50.10,One,In stock,soumission_998/index.html
3,Sharp Objects,Â£47.82,Four,In stock,sharp-objects_997/index.html
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,sapiens-a-brief-history-of-humankind_996/index...

In [70]:
df.shape

(1000, 5)

In [71]:
import pandas as pd

url = "https://scrapingtest.com/web-scraping-api"

tables = pd.read_html(url)

print("Number of tables:", len(tables))

HTTPError: HTTP Error 403: Forbidden

In [72]:
import requests

url = "https://scrapingtest.com/web-scraping-api"

response = requests.get(url)

print(response.status_code)

200

In [73]:
tables = soup.find_all("table")

print("HTML tables:", len(tables))

HTML tables: 0

In [74]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

print("HTML tables:", len(soup.find_all("table")))

HTML tables: 33

In [75]:
print(soup.title.get_text(strip=True))

Web Scraping API Benchmark, 16 Providers Compared | ScrapingTest

In [76]:
import pandas as pd

tables = pd.read_html(response.text)

print("Number of tables:", len(tables))

FileNotFoundError: [Errno 2] No such file or directory: <!DOCTYPE html><html lang="en" class="inter_b2991b2-module__9mH_6q__variable antialiased"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="preload" href="/_next/static/media/797e433ab948586e-s.p.0r6juujl39pe6.woff2" as="font" crossorigin="" type="font/woff2"/><link rel="preload" href="/_next/static/media/83afe278b6a6bb3c-s.p.2bn3s6zvc0dyp.woff2" as="font" crossorigin="" type="font/woff2"/><link rel="preload" href="/_next/static/media/caa3a2e1cccd8315-s.p.0wgildi0cnwt9.woff2" as="font" crossorigin="" type="font/woff2"/><link rel="stylesheet" href="/_next/static/chunks/0dl30l5y8wy-c.css" data-precedence="next"/><link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/16-n7qhu3dhdv.js"/><script src="/_next/static/chunks/36fbn92hx4qm6.js" async=""></script><script src="/_next/static/chunks/3az9z3aqo2km_.js" async=""></script><script src="/_next/static/chunks/0nt-cqivqhywi.js" async=""></script><script src="/_next/static/chunks/turbopack-2e2q3ulg0mjbs.js" async=""></script><script src="/_next/static/chunks/3_dg3ydki5oqk.js" async=""></script><script src="/_next/static/chunks/3w-4zb68quvf4.js" async=""></script><script src="/_next/static/chunks/2hsu5cpj6q35d.js" async=""></script><script src="/_next/static/chunks/3oe_9ghbhbz14.js" async=""></script><script src="/_next/static/chunks/3hrdkyk37bqmo.js" async=""></script><link rel="preload" href="https://www.googletagmanager.com/gtm.js?id=G-60K4PNDWYC" as="script"/><meta name="theme-color" content="#0a0a0a"/><link rel="icon" href="/logo-spider-cross.svg" type="image/svg+xml"/><meta name="next-size-adjust" content=""/><title>Web Scraping API Benchmark, 16 Providers Compared | ScrapingTest</title><meta name="description" content="Independent benchmark of 16 web scraping APIs across 20 target domains. Compare success rate, response time, P90 latency, and cost per 1,000 requests."/><meta name="application-name" content="ScrapingTest"/><meta name="author" content="ScrapingTest Research"/><meta name="keywords" content="web scraping benchmark,web scraping API comparison,scraping practice,cloudflare bypass test,turnstile test,anti-bot challenge,scraping playground"/><meta name="creator" content="ScrapingTest Research"/><meta name="publisher" content="ScrapingTest"/><meta name="robots" content="index, follow"/><meta name="googlebot" content="index, follow, max-video-preview:-1, max-image-preview:large, max-snippet:-1"/><link rel="canonical" href="https://scrapingtest.com/web-scraping-api"/><meta property="og:title" content="Web Scraping API Benchmark, 16 Providers Compared"/><meta property="og:description" content="Independent head-to-head benchmark of 16 web scraping APIs across 20 target domains."/><meta property="og:url" content="https://scrapingtest.com/web-scraping-api"/><meta property="og:image" content="https://scrapingtest.com/scraping-benchmarks.png"/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:image:alt" content="Web Scraping API Performance Index"/><meta property="og:type" content="article"/><meta property="article:published_time" content="2025-12-30"/><meta property="article:modified_time" content="2026-05-22"/><meta property="article:author" content="ScrapingTest Research"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="Web Scraping API Benchmark, 16 Providers Compared"/><meta name="twitter:description" content="Independent benchmark of 16 web scraping APIs. Updated 2026-05-22."/><meta name="twitter:image" content="https://scrapingtest.com/scraping-benchmarks.png"/><link rel="icon" href="/favicon.ico?favicon.2vob68tjqpejf.ico" sizes="256x256" type="image/x-icon"/><script>
(function() {
  try {
    var stored = localStorage.getItem('theme-storage');
    var theme = stored ? JSON.parse(stored).state.theme : 'dark';
    var isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
    if (isDark) document.documentElement.classList.add('dark');
  } catch (e) {
    document.documentElement.classList.add('dark');
  }
})();

In [77]:
import pandas as pd
from io import StringIO

tables = pd.read_html(StringIO(response.text))

print("Number of tables:", len(tables))

Number of tables: 33

In [78]:
for i, table in enumerate(tables):
    print("\n-------------------")
    print("TABLE:", i)
    print("Shape:", table.shape)
    print(table.head(3))

-------------------
TABLE: 0
Shape: (16, 5)
  API Provider Success %  Response (ms)  P90 (ms)? $/1K reqs?
0  #1Scrape.do    99.39%           4191       6993      $0.87
1     #2Decodo    95.90%          11908      17862      $0.86
2      #3Apify    95.25%          19538      29219      $7.04

-------------------
TABLE: 1
Shape: (5, 3)
    Plan   Price               Credits / volume
0   Free      $0     1K credits + 5 concurrency
1  Hobby  $29/mo   250K credits + 5 concurrency
2    Pro  $99/mo  1.5M credits + 15 concurrency

-------------------
TABLE: 2
Shape: (20, 6)
        Domain Success   Avg   P90 Cost/1K Structured
0   amazon.com  100.0%  3.4s  4.8s   $0.11          ✓
1  bestbuy.com   99.9%  4.4s  6.1s   $1.10          -
2     bing.com  100.0%  1.1s  1.5s   $0.11          -

-------------------
TABLE: 3
Shape: (5, 3)
       Plan   Price                   Credits / volume
0      Free      $0             2K requests @ 10 req/s
1   Starter  $19/mo   38K standard requests @ 10 req/s
2  Advanced  $49/mo  163K standard requests @ 25 req/s

-------------------
TABLE: 4
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com  100.0%   4.2s   6.4s   $0.50          ✓
1  bestbuy.com   79.0%  24.4s  36.6s   $1.50          -
2     bing.com  100.0%   3.8s   5.7s   $0.50          ✓

-------------------
TABLE: 5
Shape: (5, 3)
      Plan    Price                      Credits / volume
0     Free    $0/mo           $5 monthly platform credits
1  Starter   $39/mo      Increased compute + PPE discount
2    Scale  $199/mo  Higher compute + deeper PPE discount

-------------------
TABLE: 6
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com   80.0%  14.5s  21.8s   $5.00          ✓
1  bestbuy.com  100.0%  11.6s  17.3s  $10.15          ✓
2     bing.com  100.0%  13.3s  18.1s   $6.10          ✓

-------------------
TABLE: 7
Shape: (5, 3)
            Plan       Price         Credits / volume
0  Pay As You Go  $1.50 / 1K            no commitment
1         Growth     $499/mo  380K results ($1.30/1K)
2       Business     $999/mo  900K results ($1.10/1K)

-------------------
TABLE: 8
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com   96.7%   3.4s   4.8s   $1.50          ✓
1  bestbuy.com   83.3%  10.3s  26.8s   $2.50          ✓
2     bing.com  100.0%   4.5s  11.6s   $1.50          ✓

-------------------
TABLE: 9
Shape: (5, 3)
         Plan    Price     Credits / volume
0        Free       $0  1,000 credits/month
1   Discovery   $30/mo         200K credits
2  Production  $100/mo           1M credits

-------------------
TABLE: 10
Shape: (20, 6)
        Domain Success   Avg   P90 Cost/1K Structured
0   amazon.com  100.0%  4.7s  6.2s   $3.75          -
1  bestbuy.com   90.0%  5.5s  8.3s   $3.37          -
2     bing.com   98.0%  2.6s  3.9s   $0.15          -

-------------------
TABLE: 11
Shape: (5, 3)
                    Plan   Price               Credits / volume
0             Free Trial      $0  2,000 Web Scraper API results
1  Web Scraper API Micro  $49/mo             98K Amazon results
2    Web Unblocker Micro  $75/mo                  8GB bandwidth

-------------------
TABLE: 12
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com  100.0%  10.2s  15.3s   $7.00          ✓
1  bestbuy.com   75.0%  34.1s  51.1s   $7.00          ✓
2     bing.com  100.0%   7.0s  10.5s   $7.00          ✓

-------------------
TABLE: 13
Shape: (5, 3)
      Plan   Price                  Credits / volume
0     Free      $0  500 credits one-time, 10 req/min
1  Starter  $17/mo         10K credits + 100 req/min
2   Growth  $85/mo        100K credits + 500 req/min

-------------------
TABLE: 14
Shape: (20, 6)
        Domain Success   Avg    P90 Cost/1K Structured
0   amazon.com  100.0%  6.9s  10.4s   $2.00          -
1  bestbuy.com    0.0%  0.0s   0.0s   $0.00          -
2     bing.com  100.0%  0.6s   0.8s   $2.00          -

-------------------
TABLE: 15
Shape: (5, 3)
      Plan   Price       Credits / volume
0    Trial      $0  5,000 API calls/month
1  Starter  $19/mo        7,000 API calls
2    Basic  $49/mo       20,000 API calls

-------------------
TABLE: 16
Shape: (20, 6)
        Domain Success   Avg    P90 Cost/1K Structured
0   amazon.com  100.0%  2.9s   4.8s   $2.45          ✓
1  bestbuy.com   87.0%  7.4s  16.4s  $12.25          ✓
2     bing.com   51.0%  2.2s   6.6s   $2.45          ✓

-------------------
TABLE: 17
Shape: (5, 3)
         Plan   Price               Credits / volume
0  Free Trial      $0         1,000 credits one-time
1   Freelance  $49/mo  250K credits + 10 concurrency
2     Startup  $99/mo    1M credits + 50 concurrency

-------------------
TABLE: 18
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com  100.0%   4.9s   8.9s   $0.20          ✓
1  bestbuy.com  100.0%  47.3s  60.4s   $4.90          -
2     bing.com  100.0%   0.9s   1.7s   $0.20          -

-------------------
TABLE: 19
Shape: (5, 3)
              Plan      Price                     Credits / volume
0       Free Trial  $5 credit                   30-day PAYG access
1    Pay As You Go  $0 commit  $100/mo spending limit, 0% discount
2  $200 Commitment    $100/mo             $400 limit, 40% discount

-------------------
TABLE: 20
Shape: (20, 6)
        Domain Success   Avg    P90 Cost/1K Structured
0   amazon.com  100.0%  3.0s   4.5s   $3.50          -
1  bestbuy.com   70.0%  5.7s  13.2s   $3.50          -
2     bing.com  100.0%  0.9s   1.5s   $3.50          -

-------------------
TABLE: 21
Shape: (5, 3)
        Plan       Price             Credits / volume
0  Developer   $69.99/mo  250K basic / 10K premium+JS
1    Startup  $129.99/mo    1M basic / 40K premium+JS
2   Business  $299.99/mo   3M basic / 120K premium+JS

-------------------
TABLE: 22
Shape: (20, 6)
        Domain Success   Avg   P90 Cost/1K Structured
0   amazon.com   74.0%  1.9s  2.8s   $0.28          ✓
1  bestbuy.com    0.0%  0.0s  0.0s   $0.00          -
2     bing.com  100.0%  5.6s  8.3s   $7.00          -

-------------------
TABLE: 23
Shape: (5, 3)
         Plan   Price              Credits / volume
0  Free Trial      $0      1,000 credits (one-time)
1        LITE  $40/mo  200K credits + 5 concurrency
2    STANDARD  $90/mo   1M credits + 50 concurrency

-------------------
TABLE: 24
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com  100.0%   3.6s   8.3s   $0.20          ✓
1  bestbuy.com   53.0%  12.4s  19.1s   $0.20          -
2     bing.com  100.0%   5.3s   7.2s   $0.20          ✓

-------------------
TABLE: 25
Shape: (5, 3)
      Plan    Price                      Credits / volume
0     Free       $0                   1,000 credits/month
1    Hobby   $49/mo  100K credits + 20 threads, US/EU geo
2  Startup  $149/mo    1M credits + 50 threads, US/EU geo

-------------------
TABLE: 26
Shape: (20, 6)
        Domain Success   Avg    P90 Cost/1K Structured
0   amazon.com  100.0%  7.3s  10.9s   $2.45          ✓
1  bestbuy.com  100.0%  1.2s   2.1s  $36.75          -
2     bing.com  100.0%  1.4s   2.1s  $26.95          -

-------------------
TABLE: 27
Shape: (5, 3)
       Plan   Price              Credits / volume
0      Free      $0    500 credits one-time trial
1     Hobby  $16/mo    3K credits (billed yearly)
2  Standard  $83/mo  100K credits (billed yearly)

-------------------
TABLE: 28
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com   53.3%   6.3s  22.6s   $5.33          -
1  bestbuy.com   33.3%  14.2s  23.0s  $26.65          -
2     bing.com  100.0%   0.4s   0.5s   $5.33          -

-------------------
TABLE: 29
Shape: (4, 3)
         Plan   Price Credits / volume
0        Free      $0      10K credits
1  Enthusiast  $19/mo     100K credits
2     Startup  $49/mo     500K credits

-------------------
TABLE: 30
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com   96.0%  17.8s  56.6s   $0.19          -
1  bestbuy.com   38.0%  13.3s  57.7s   $1.90          -
2     bing.com  100.0%  39.9s  46.8s   $0.19          -

-------------------
TABLE: 31
Shape: (4, 3)
         Plan    Price Credits / volume
0     Starter   $25/mo   1,000 searches
1   Developer   $75/mo   5,000 searches
2  Production  $150/mo  15,000 searches

-------------------
TABLE: 32
Shape: (20, 6)
        Domain Success    Avg    P90 Cost/1K Structured
0   amazon.com    0.0%   0.0s   0.0s  $25.00          ✓
1  bestbuy.com    0.0%   0.0s   0.0s  $25.00          -
2     bing.com  100.0%  13.0s  18.0s  $25.00          ✓

In [79]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO

url = "https://scrapingtest.com/web-scraping-api"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

print("HTML tables:", len(soup.find_all("table")))

tables = pd.read_html(StringIO(response.text))

print("Pandas tables:", len(tables))

for i, table in enumerate(tables):
    print(i, table.columns.tolist())

Status: 200
HTML tables: 33
Pandas tables: 33
0 ['API Provider', 'Success %', 'Response (ms)', 'P90 (ms)?', '$/1K reqs?']
1 ['Plan', 'Price', 'Credits / volume']
2 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
3 ['Plan', 'Price', 'Credits / volume']
4 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
5 ['Plan', 'Price', 'Credits / volume']
6 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
7 ['Plan', 'Price', 'Credits / volume']
8 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
9 ['Plan', 'Price', 'Credits / volume']
10 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
11 ['Plan', 'Price', 'Credits / volume']
12 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
13 ['Plan', 'Price', 'Credits / volume']
14 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
15 ['Plan', 'Price', 'Credits / volume']
16 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
17 ['Plan', 'Price', 'Credits / volume']
18 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
19 ['Plan', 'Price', 'Credits / volume']
20 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
21 ['Plan', 'Price', 'Credits / volume']
22 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
23 ['Plan', 'Price', 'Credits / volume']
24 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
25 ['Plan', 'Price', 'Credits / volume']
26 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
27 ['Plan', 'Price', 'Credits / volume']
28 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
29 ['Plan', 'Price', 'Credits / volume']
30 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']
31 ['Plan', 'Price', 'Credits / volume']
32 ['Domain', 'Success', 'Avg', 'P90', 'Cost/1K', 'Structured']

In [80]:
for i, table in enumerate(tables):
    if "API PROVIDER" in table.columns:
        print("Found table:", i)
        df = table
        break

In [81]:
df

,book_name,price,rating,availability,url
0,A Light in the Attic,Â£51.77,Three,In stock,a-light-in-the-attic_1000/index.html
1,Tipping the Velvet,Â£53.74,One,In stock,tipping-the-velvet_999/index.html
2,Soumission,Â£50.10,One,In stock,soumission_998/index.html
3,Sharp Objects,Â£47.82,Four,In stock,sharp-objects_997/index.html
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,sapiens-a-brief-history-of-humankind_996/index...
...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,One,In stock,alice-in-wonderland-alices-adventures-in-wonde...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,Four,In stock,ajin-demi-human-volume-1-ajin-demi-human-1_4/i...
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,Five,In stock,a-spys-devotion-the-regency-spies-of-london-1_...
998,1st to Die (Women's Murder Club #1),Â£53.98,One,In stock,1st-to-die-womens-murder-club-1_2/index.html
999,"1,000 Places to See Before You Die",Â£26.08,Five,In stock,1000-places-to-see-before-you-die_1/index.html

In [82]:
df= table[15]

KeyError: 15